spring:
  kafka:
    consumer:
      bootstrap-servers: 100.94.169.124:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-records: 1000
      auto-offset-reset: latest
server:
  port: 9998
influx:
  token: huawei-token
  bucket: public
  url: http://100.94.169.124:8086
  org: huawei